name: Make Release

on:
  workflow_dispatch: 
    inputs:
      release_tag:
        description: "Release Tag"
        required: true
        type: string
  
jobs:
  # build-docker: 
  #   uses: "./.github/workflows/build-and-release-docker.yml"
  #   with:
  #     enabled: true
  #     release_tag: "${{ inputs.release_tag }}"
  #     build_number: "${{ inputs.release_tag }}"
  #     elyra_branch: "master"
  #     unskript_branch: "master"
  #     celltoolbar_branch: "master"
  #     snippet_branch: "master"
  #   secrets: inherit

  make-release:
    runs-on: ubuntu-latest
    #needs: ["build-docker"]
    steps:
      - uses: actions/checkout@v3
      - name: Build Change Log
        uses: mikepenz/release-changelog-builder-action@{latest-release}
        env:
          GITHUB_TOKEN: ${{ secrets.BUILDER_PAT }}