name: Make Release

on:
  workflow_dispatch: 
    inputs:
      release_tag:
        description: "Release Tag"
        required: true
        type: string
  
jobs:
  # build-docker: 
  #   needs: ['bump-version']
  #   uses: "./.github/workflows/build-and-release-docker.yml"
  #   with:
  #     enabled: true
  #     release_tag: "${{ inputs.release_tag }}"
  #     build_number: "${{ inputs.release_tag }}"
  #     elyra_branch: "master"
  #     unskript_branch: "master"
  #     celltoolbar_branch: "master"
  #     snippet_branch: "master"
  #   secrets: inherit

  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - run: git fetch --prune --unshallow
      - name: Bump version and push 
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.BUILDER_PAT }}
          dry_run: true
          default_bump: minor
          default_prerelease_bump: minor
          append_to_pre_release_tag: ""
          tag_prefix: ""

    #  - name: Create Docker 
    #   uses: "./.github/workflows/build-and-release-docker.yml"
    #   with:
    #     enabled: true
    #     release_tag: "${{ inputs.release_tag }}"
    #     build_number: "${{ inputs.release_tag }}"
    #     elyra_branch: "master"
    #     unskript_branch: "master"
    #     celltoolbar_branch: "master"
    #     snippet_branch: "master"
    #   secrets: inherit      
      
      - name: Create Docker ReleaseNotes
        id: create_docker_rn
        run: |
          echo "## Download Latest Docker" > /tmp/docker_rn.md
          echo "\`\`\`HELLO WORLD\`\`\`" >> /tmp/docker_rn.md
          TAG_NAME=$(echo ${{ steps.tag_version.outputs.new_tag }} | cut -d '-' -f 1)
          echo "TAGNAME: $TAG_NAME"
          echo "GITHUB_ONLY_TAG=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "${{ steps.create_docker_rn.output.GITHUB_ONLY_TAG }}" >> /tmp/docker_rn.md
          echo "${{ steps.tag_version.outputs.changelog }}" >> /tmp/docker_rn.md
          cat /tmp/docker_rn.md

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_version }}
          name: Release ${{ steps.tag_version.outputs.new_version }}
          #body: ${{ steps.steps.tag_version.outputs.changelog }}
          bodyFile: "/tmp/docker_rn.md"
          generateReleaseNotes: true
          makeLatest: legacy
          omitBody: false
          omitBodyDuringUpdate: false
          omitDraftDuringUpdate: false
          omitName: false
          omitNameDuringUpdate: false
          omitPrereleaseDuringUpdate: false
          removeArtifacts: false
          replacesArtifacts: true
          skipIfReleaseExists: false
          updateOnlyUnreleased: false