name: Make Release
on:
  workflow_dispatch:
    inputs:
      releasetag:
        description: "Release Tag"
        required: true
        type: string

env:
  RELEASE_TAG: ${{ github.event.inputs.releasetag }}
  

jobs:
  make-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
        with:
            ref: '${{ github.event.inputs.releasetag }}'
      - uses: "actions/github-script@v6"
        with:
          github-token: "${{ secrets.BUILDER_PAT_ENCODED }}"
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_TAG,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
              });

              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }
