name: Make Release

on:
  workflow_dispatch: 
    inputs:
      release_tag:
        description: "Release Tag"
        required: true
        type: string
  
jobs:
  build-docker: 
    uses: "./.github/workflows/build-and-release-docker.yml"
    with:
      enabled: true
      release_tag: "${{ inputs.release_tag }}"
      build_number: "${{ inputs.release_tag }}"
      elyra_branch: "master"
      unskript_branch: "master"
      celltoolbar_branch: "master"
      snippet_branch: "master"


  make-release:
    runs-on: ubuntu-latest
    needs: ["build-docker"]
    steps:
      - uses: actions/checkout@v3 
        with:
            ref: '${{ inputs.release_tag }}'
      - uses: "actions/github-script@v6"
        with:
          github-token: "${{ secrets.BUILDER_PAT_ENCODED }}"
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_TAG,
                owner: context.repo.owner,
                prerelease: false,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
              });

              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }