name: Make Release

on:
  workflow_dispatch: 
    inputs:
      release_tag:
        description: "Release Tag"
        required: true
        type: string
  
jobs:
  # build-docker: 
  #   uses: "./.github/workflows/build-and-release-docker.yml"
  #   with:
  #     enabled: true
  #     release_tag: "${{ inputs.release_tag }}"
  #     build_number: "${{ inputs.release_tag }}"
  #     elyra_branch: "master"
  #     unskript_branch: "master"
  #     celltoolbar_branch: "master"
  #     snippet_branch: "master"
  #   secrets: inherit

  make-release:
    runs-on: ubuntu-latest
    #needs: ["build-docker"]
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.BUILDER_PAT }}
          dry_run: true
          default_bump: minor
          default_prerelease_bump: minor
          tag_prefix: " "
          custom_tag: ${{ inputs.release_tag }}
      - name: Create Docker Information Content
        run: |
          echo "## Download Latest Docker" > /tmp/docker_release.txt
          echo "```DOWNLOAD INSTRUCTION HERE```" >> /tmp/docker_release.txt
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          bodyFile: "/tmp/docker_release.txt"
          generateReleaseNotes: true
          makeLatest: legacy
          omitBody: false
          omitBodyDuringUpdate: false
          omitDraftDuringUpdate: false
          omitName: false
          omitNameDuringUpdate: false
          omitPrereleaseDuringUpdate: false
          removeArtifacts: false
          replacesArtifacts: true
          skipIfReleaseExists: false
          updateOnlyUnreleased: false